#!/usr/bin/env python3
"""Write Prover.toml inputs for examples/ from live Ethereum mainnet data.

  examples/account_balance  — an EOA's ETH balance and nonce
  examples/erc20_balance    — a holder's USDC balance (account + storage proof)

Both proofs are verified here (hash chain + expected value via eth_call) before
being written, so a failing example means a circuit problem, not a bad input.

Usage: python3 scripts/generate_example_inputs.py [RPC_URL]
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import generate_test_vectors as gtv  # noqa: E402
from _keccak import keccak256, to_nibbles  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# An account with a long history: non-zero balance and a high nonce.
EOA = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"

# USDC (FiatTokenV2_2). Storage lives in the proxy, which is where balanceOf
# reads and writes it, so that is the account we prove.
USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
USDC_BALANCES_SLOT = 9  # must match BALANCES_SLOT in the example circuit

# Exchange hot wallets, tried in order until one has a non-zero balance.
HOLDER_CANDIDATES = [
    "0x28C6c06298d514Db089934071355E5743bf21d60",  # Binance 14
    "0x5041ed759Dd4aFc3a72b8192C143F72f4724081A",  # OKX
    "0xF977814e90dA44bFA03b6295A0616a897441aceC",  # Binance 8
]

MAX_ACCOUNT_PATH = 10  # must match the examples' MAX_ACCOUNT_PATH
MAX_STORAGE_PATH = 9  # must match erc20_balance's MAX_STORAGE_PATH


def pad32(value: int) -> bytes:
    return value.to_bytes(32, "big")


def address_mapping_slot(address: str, slot: int) -> bytes:
    """keccak(pad32(address) ‖ pad32(slot)) — mirrors slot_key::address_mapping_slot."""
    addr = bytes(gtv.hex_bytes(address))
    assert len(addr) == 20
    return keccak256(b"\x00" * 12 + addr + pad32(slot))


def call_balance_of(token: str, holder: str, block: str) -> int:
    selector = keccak256(b"balanceOf(address)")[:4]
    data = "0x" + (selector + b"\x00" * 12 + bytes(gtv.hex_bytes(holder))).hex()
    result = gtv.rpc("eth_call", [{"to": token, "data": data}, block])
    return int(result, 16)


# ---------------- TOML emission ----------------


def toml_strings(values) -> str:
    """Integers as quoted decimals: u64 limbs overflow TOML's signed 64-bit int."""
    return "[" + ", ".join(f'"{v}"' for v in values) + "]"


def toml_bools(values) -> str:
    return "[" + ", ".join("true" if v else "false" for v in values) + "]"


def node_table(name: str, node) -> str:
    rows = ", ".join(toml_strings(row) for row in node["rows"])
    return (
        f"[[{name}]]\n"
        f"rows = [{rows}]\n"
        f"row_exist = {toml_bools(node['row_exist'])}\n"
        f'node_type = "{node["node_type"]}"\n'
    )


def pad_nodes(nodes: list, length: int) -> list:
    assert len(nodes) <= length, f"proof path {len(nodes)} nodes > max {length}"
    return nodes + [gtv.zero_node() for _ in range(length - len(nodes))]


def account_table(address: str, proof) -> str:
    nonce = gtv.quantity_bytes(int(proof["nonce"], 16))
    balance = gtv.quantity_bytes(int(proof["balance"], 16))
    return (
        "[account]\n"
        f"nonce = {toml_strings(gtv.pad_to(nonce, 8))}\n"
        f"balance = {toml_strings(gtv.pad_to(balance, 32))}\n"
        f"address = {toml_strings(gtv.hex_bytes(address))}\n"
        f'nonce_length = "{len(nonce)}"\n'
        f'balance_length = "{len(balance)}"\n'
        f"storage_hash = {toml_strings(gtv.to_u64_limbs(gtv.hex_bytes(proof['storageHash'])))}\n"
        f"code_hash = {toml_strings(gtv.to_u64_limbs(gtv.hex_bytes(proof['codeHash'])))}\n"
    )


# ---------------- examples ----------------


def account_balance_example(block_number: str, state_root: list[int]) -> None:
    proof = gtv.rpc("eth_getProof", [EOA, [], block_number])
    path = [gtv.parse_node(n) for n in proof["accountProof"][:-1]]
    gtv.check_hash_chain(
        proof["accountProof"][:-1],
        path,
        gtv.limbs_to_bytes(state_root),
        to_nibbles(keccak256(bytes(gtv.hex_bytes(EOA)))),
    )

    balance = int(proof["balance"], 16)
    nonce = int(proof["nonce"], 16)

    out = (
        f"# Generated by scripts/generate_example_inputs.py — real mainnet data.\n"
        f"# Account {EOA} at block {int(block_number, 16)}.\n"
        f"# Expected output: balance {balance} wei, nonce {nonce}.\n"
        f"state_root = {toml_strings(state_root)}\n"
        f"address = {toml_strings(gtv.hex_bytes(EOA))}\n"
        f'node_length = "{len(path)}"\n'
        f"\n{account_table(EOA, proof)}\n"
        + "\n".join(node_table("nodes", n) for n in pad_nodes(path, MAX_ACCOUNT_PATH))
    )
    (ROOT / "examples" / "account_balance" / "Prover.toml").write_text(out)
    print(
        f"account_balance: {len(path)}-node path, balance {balance} wei, nonce {nonce}"
    )
    return balance, nonce


def erc20_balance_example(block_number: str, state_root: list[int]) -> None:
    holder = None
    for candidate in HOLDER_CANDIDATES:
        if call_balance_of(USDC, candidate, block_number) > 0:
            holder = candidate
            break
    assert holder, "no candidate holder had a non-zero USDC balance"
    expected = call_balance_of(USDC, holder, block_number)

    slot_key = address_mapping_slot(holder, USDC_BALANCES_SLOT)
    proof = gtv.rpc("eth_getProof", [USDC, ["0x" + slot_key.hex()], block_number])
    slot_proof = proof["storageProof"][0]
    value = int(slot_proof["value"], 16)

    # If the declaration slot were wrong, the proof would come back empty or
    # hold something other than the balance.
    assert value == expected, (
        f"slot {USDC_BALANCES_SLOT} holds {value}, but balanceOf says {expected} — "
        "wrong storage layout?"
    )

    account_path = [gtv.parse_node(n) for n in proof["accountProof"][:-1]]
    storage_path = [gtv.parse_node(n) for n in slot_proof["proof"][:-1]]
    gtv.check_hash_chain(
        proof["accountProof"][:-1],
        account_path,
        gtv.limbs_to_bytes(state_root),
        to_nibbles(keccak256(bytes(gtv.hex_bytes(USDC)))),
    )
    gtv.check_hash_chain(
        slot_proof["proof"][:-1],
        storage_path,
        bytes(gtv.hex_bytes(proof["storageHash"])),
        to_nibbles(keccak256(slot_key)),
    )

    value_bytes = gtv.quantity_bytes(value)
    out = (
        f"# Generated by scripts/generate_example_inputs.py — real mainnet data.\n"
        f"# USDC ({USDC}) balances[{holder}]\n"
        f"# at block {int(block_number, 16)}. Expected output: {value} "
        f"({value / 10**6:,.2f} USDC).\n"
        f"state_root = {toml_strings(state_root)}\n"
        f"token = {toml_strings(gtv.hex_bytes(USDC))}\n"
        f"holder = {toml_strings(gtv.hex_bytes(holder))}\n"
        f'account_node_length = "{len(account_path)}"\n'
        f'storage_node_length = "{len(storage_path)}"\n'
        f"\n{account_table(USDC, proof)}\n"
        f"[balance_slot]\n"
        f"value = {toml_strings(gtv.pad_to(value_bytes, 32))}\n"
        f'value_length = "{len(value_bytes)}"\n\n'
        + "\n".join(
            node_table("account_nodes", n) for n in pad_nodes(account_path, MAX_ACCOUNT_PATH)
        )
        + "\n"
        + "\n".join(
            node_table("storage_nodes", n) for n in pad_nodes(storage_path, MAX_STORAGE_PATH)
        )
    )
    (ROOT / "examples" / "erc20_balance" / "Prover.toml").write_text(out)
    print(
        f"erc20_balance: holder {holder}, {len(account_path)}-node account path, "
        f"{len(storage_path)}-node storage path, balance {value} ({value / 10**6:,.2f} USDC)"
    )
    return holder, value


def main():
    block = gtv.rpc("eth_getBlockByNumber", ["finalized", False])
    block_number = block["number"]
    state_root = gtv.to_u64_limbs(gtv.hex_bytes(block["stateRoot"]))
    print(f"block {int(block_number, 16)} state root {block['stateRoot']}")

    account_balance_example(block_number, state_root)
    erc20_balance_example(block_number, state_root)
    print("\nrun `nargo execute` in each example directory to verify")


if __name__ == "__main__":
    main()
